"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisScroll from "@/components/lennis-scroll";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Ayase Atalier",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LenisScroll>
      <html lang="en" className=" font-['Inter Tight']">
        <body className={inter.className}>{children}</body>
      </html>
    </LenisScroll>
  );
}
